name: Deploy Production

on:
  workflow_run:
    workflows: ["Build & Push Production Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Get latest tag
        id: tag
        run: |
          git fetch --tags

          LAST_TAG=$(git tag --list "v*" --sort=-v:refname | head -n 1)

          echo "IMAGE_TAG=prod-$LAST_TAG" >> $GITHUB_ENV

      - name: Deploy VPS
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << EOF

          cd /home/kevine/deploy/Portfolio-Web

          export IMAGE_TAG=${IMAGE_TAG}

          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d --remove-orphans

          docker image prune -af

          EOF