name: Deploy Production

on:
  workflow_run:
    workflows:
      - "Build & Push Production Image"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest tag
        id: tag
        run: |
          LAST_TAG=$(git tag --list "v*" --sort=-v:refname | head -n 1)

          echo "IMAGE_TAG=prod-$LAST_TAG" >> $GITHUB_ENV

          echo "Using IMAGE_TAG=prod-$LAST_TAG"

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << EOF

          cd /home/kevine/deploy/Portfolio-Web
          
          echo "→ Pull du code..."
          git fetch origin
          git reset --hard origin/main

          echo "→ Génération du .env..."
          cat > .env << 'ENVEOF'
          
          ENVEOF
          chmod 600 .env

          echo "→ Build et démarrage..."

          export IMAGE_TAG=${IMAGE_TAG}

          docker compose -f docker-compose.prod.yml pull

          docker compose -f docker-compose.prod.yml up -d --remove-orphans

          docker image prune -af

          EOF